<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="NationalInstruments.Common">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\National Instruments\Measurement Studio\DotNET\v4.0\AnyCPU\NationalInstruments.Common 19.1.40\NationalInstruments.Common.dll</HintPath>
    </Reference>
    <Reference Include="NationalInstruments.DAQmx">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\National Instruments\MeasurementStudioVS2010\DotNET\Assemblies (64-bit)\24.0.40.49417\NationalInstruments.DAQmx.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>