<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Util\CircularBuffer\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DelsysAPI" Version="2.7.0.1239-dev" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DelsysNICommon\DelsysNICommon\DelsysNICommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Ivi.Visa">
      <HintPath>..\DelsysNICommon\NI_DLLs\Ni.Visa\Ivi.Visa.dll</HintPath>
    </Reference>
    <Reference Include="NationalInstruments.Visa">
      <HintPath>..\DelsysNICommon\NI_DLLs\Ni.Visa\NationalInstruments.Visa.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
