<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Platforms>AnyCPU;x86</Platforms>
    <OutputType>Library</OutputType>
  </PropertyGroup>


  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <Optimize>True</Optimize>
  </PropertyGroup>


  <ItemGroup>
    <Reference Include="NationalInstruments.Common">
      <HintPath>C:\Program Files\National Instruments\Measurement Studio\DotNET\v4.0\AnyCPU\NationalInstruments.Common 19.1.40\NationalInstruments.Common.dll</HintPath>
    </Reference>
    <Reference Include="NationalInstruments.DAQmx">
      <HintPath>C:\Program Files (x86)\National Instruments\MeasurementStudioVS2010\DotNET\Assemblies\24.0.40.49417\NationalInstruments.DAQmx.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>